apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.db.name }}-app-user"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: app
  password: "{{ .Values.db.appPassword | default "app123" }}"