apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.db.instances }}
  storage:
    {{ .Values.db.size }}